import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import '../../../styles/admin/admin.css';

type Employee = { id:string; nama:string; jabatan?:string; departemen?:string; status_aktif?:boolean; email?:string };
type Attendance = { id?:string|number; id_karyawan?:string; nama?:string; tanggal?:string; jam_masuk?:string; jam_pulang?:string; status?:string; keterlambatan_menit?:number|string; lembur_menit?:number|string };
type Props = { employees:Employee[]; attendance:Attendance[]; onNavigate:(key:any)=>void };
type Tab = 'executive'|'workforce'|'alerts'|'actions';

const isoToday=()=>new Date().toISOString().slice(0,10);
const download=(name:string,content:string,type='text/csv;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};

export default function ProfessionalSuite({employees,attendance,onNavigate}:Props){
 const [tab,setTab]=useState<Tab>('executive');
 const active=employees.filter(x=>x.status_aktif!==false);
 const today=attendance.filter(x=>x.tanggal===isoToday());
 const late=today.filter(x=>Number(x.keterlambatan_menit||0)>0 || /late|terlambat/i.test(String(x.status||'')));
 const openActions=useMemo(()=>[
   {id:'attendance',title:'Review attendance exceptions',desc:`${late.length} record perlu ditinjau`,tone:late.length?'warning':'good',go:'attendance'},
   {id:'leave',title:'Review leave requests',desc:'Buka pusat persetujuan untuk item pending',tone:'neutral',go:'approvals'},
   {id:'payroll',title:'Payroll readiness check',desc:'Validasi payroll sebelum publish',tone:'neutral',go:'payroll'},
   {id:'security',title:'Security review',desc:'Periksa RLS, role dan activity log',tone:'neutral',go:'security-v21'},
 ],[late.length]);
 const departments=useMemo(()=>{const m:Record<string,number>={};active.forEach(e=>{const d=e.departemen||'Belum diatur';m[d]=(m[d]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,6)},[active]);
 const attendanceRate=active.length?Math.min(100,Math.round(today.length/active.length*100)):0;
 const exportExecutive=()=>{const rows=[['Metric','Value'],['Active employees',String(active.length)],['Attendance today',String(today.length)],['Attendance rate',`${attendanceRate}%`],['Late records',String(late.length)],['Generated at',new Date().toISOString()]];download('moonx-executive-report.csv',rows.map(r=>r.join(',')).join('\n'))};
 return <div className="professional-suite">
  <div className="page-heading"><div><span className="eyebrow">PROFESSIONAL OPERATIONS</span><h1>Executive Command Center</h1><p>Pusat kendali operasional untuk keputusan HR harian, tanpa mengubah database.</p></div><div className="heading-actions"><button className="secondary" onClick={exportExecutive}>Export Executive Report</button><button className="primary" onClick={()=>onNavigate('reports')}>Buka Reporting</button></div></div>
  <div className="branch-tabs">{([['executive','Executive'],['workforce','Workforce'],['alerts','Risk & Alerts'],['actions','Action Center']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='executive'&&<>
   <div className="stat-grid executive-stats"><div className="stat-card"><span>Active Workforce</span><strong>{active.length}</strong><small>{employees.length-active.length} nonaktif</small></div><div className="stat-card"><span>Attendance Today</span><strong>{attendanceRate}%</strong><small>{today.length} record tercatat</small></div><div className="stat-card"><span>Exceptions</span><strong>{late.length}</strong><small>Perlu review</small></div><div className="stat-card"><span>Data Coverage</span><strong>{employees.length?Math.round(attendance.length/Math.max(1,employees.length)):'0'}</strong><small>record / employee</small></div></div>
   <div className="dashboard-grid-top"><div className="panel"><div className="panel-head"><div><span className="eyebrow">WORKFORCE MIX</span><h2>Organisasi</h2><p>Distribusi active workforce per departemen.</p></div></div><div className="department-bars">{departments.length?departments.map(([d,n])=><div className="dept-row" key={d}><div className="dept-label"><span>{d}</span><b>{n}</b></div><div className="progress"><span style={{width:`${Math.round(n/Math.max(...departments.map(x=>x[1]))*100)}%`}}/></div></div>):<div className="empty-module"><h3>Belum ada data</h3><p>Departemen akan tampil setelah workforce tersedia.</p></div>}</div></div><div className="panel attendance-health"><div className="panel-head"><div><span className="eyebrow">READINESS</span><h2>Operational Readiness</h2><p>Indikator ringkas sebelum HR melakukan aksi penting.</p></div></div><div className="health-ring" style={{'--rate':`${attendanceRate*3.6}deg`} as CSSProperties}><div><strong>{attendanceRate}%</strong><small>Coverage</small></div></div><div className="health-legend"><div><i className="dot present"/><span>Attendance captured</span><b>{today.length}</b></div><div><i className="dot late"/><span>Exceptions</span><b>{late.length}</b></div><div><i className="dot absent"/><span>Workforce</span><b>{active.length}</b></div></div></div></div>
   <div className="dashboard-grid-bottom"><div className="panel"><div className="panel-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Attendance Feed</h2></div><button className="link-btn" onClick={()=>onNavigate('attendance')}>Lihat semua</button></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Tanggal</th><th>Masuk</th><th>Status</th></tr></thead><tbody>{attendance.slice(0,8).map((a,i)=><tr key={a.id||i}><td><b>{a.nama||a.id_karyawan||'—'}</b></td><td>{a.tanggal||'—'}</td><td>{a.jam_masuk||'—'}</td><td><span className="status">{a.status||'Tercatat'}</span></td></tr>)}{!attendance.length&&<tr><td colSpan={4}>Belum ada aktivitas.</td></tr>}</tbody></table></div></div><div className="panel quick executive-quick"><div className="panel-head"><div><span className="eyebrow">QUICK WORKFLOWS</span><h2>Proses Utama</h2></div></div><button className="quick-action" onClick={()=>onNavigate('employee-add')}>Tambah karyawan <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('approvals')}>Pusat persetujuan <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('audit')}>Audit activity <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('system-health')}>System health <span>›</span></button></div></div>
  </>}
  {tab==='workforce'&&<div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">WORKFORCE DIRECTORY</span><h2>Workforce Quality</h2><p>Data quality checks yang bisa dijalankan tanpa perubahan schema.</p></div></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Departemen</th><th>Email</th><th>Status</th><th>Quality</th></tr></thead><tbody>{employees.map(e=>{const issues=[!e.email?'Email kosong':'',!e.departemen?'Departemen kosong':'',!e.jabatan?'Jabatan kosong':''].filter(Boolean);return <tr key={e.id}><td><b>{e.nama}</b></td><td>{e.departemen||'—'}</td><td>{e.email||'—'}</td><td>{e.status_aktif===false?'Nonaktif':'Aktif'}</td><td><span className={`status ${issues.length?'orange':'green'}`}>{issues.length?`${issues.length} issue`:'Ready'}</span></td></tr>})}</tbody></table></div></div>}
  {tab==='alerts'&&<div className="content-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">RISK MONITOR</span><h2>Perhatian</h2><p>Signal berbasis data yang sudah tersedia di aplikasi.</p></div></div>{late.length?<div className="alert-list">{late.slice(0,20).map((a,i)=><div className="alert-row" key={a.id||i}><span className="status orange">Review</span><div><b>{a.nama||a.id_karyawan||'Karyawan'}</b><small>{a.tanggal||'Hari ini'} · terlambat {Number(a.keterlambatan_menit||0)} menit</small></div><button className="link-btn" onClick={()=>onNavigate('late')}>Buka</button></div>)}</div>:<div className="empty-module"><h3>Tidak ada exception hari ini</h3><p>Attendance hari ini tidak menunjukkan keterlambatan yang terdeteksi.</p></div>}</div><div className="panel"><div className="panel-head"><div><span className="eyebrow">DATA QUALITY</span><h2>Checklist</h2></div></div><div className="check-list"><div><b>Workforce loaded</b><span className="status green">OK</span></div><div><b>Attendance feed</b><span className={`status ${today.length?'green':'orange'}`}>{today.length?'OK':'Review'}</span></div><div><b>Employee contact coverage</b><span className={`status ${employees.filter(e=>e.email).length===employees.length?'green':'orange'}`}>{employees.filter(e=>e.email).length}/{employees.length}</span></div></div></div></div>}
  {tab==='actions'&&<div className="content-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">ACTION CENTER</span><h2>Today's Work Queue</h2><p>Shortcut terstruktur untuk pekerjaan HR yang umum.</p></div></div><div className="action-card-grid">{openActions.map(a=><button className="action-card" key={a.id} onClick={()=>onNavigate(a.go)}><span className={`status ${a.tone==='warning'?'orange':a.tone==='good'?'green':'blue'}`}>{a.tone==='warning'?'Attention':'Ready'}</span><b>{a.title}</b><small>{a.desc}</small><em>Open workflow →</em></button>)}</div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">NEXT PHASE</span><h2>Database-backed Automation</h2><p>UI ini sengaja dibuat siap untuk dihubungkan ke SQL pada fase berikutnya.</p></div></div><ul className="roadmap-list"><li>Approval queue persistence</li><li>Notification preferences</li><li>Audit event persistence</li><li>Scheduled HR jobs</li><li>AI-assisted anomaly review dengan human approval</li></ul></div></div>}
 </div>;
}
