import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabase/client';
import '../../../styles/admin/admin.css';

type Row=Record<string, any>;
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>new Date().toISOString().slice(0,7);
const Status=({v}:{v:string})=><span className="status blue">{v||'—'}</span>;

export function PayrollEngineV9(){
 const [tab,setTab]=useState<'engine'|'preflight'|'thr'|'rules'>('engine');
 const [period,setPeriod]=useState(month()),[periods,setPeriods]=useState<Row[]>([]),[rows,setRows]=useState<Row[]>([]),[events,setEvents]=useState<Row[]>([]),[preflight,setPreflight]=useState<Row[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const [thr,setThr]=useState({year:String(new Date().getFullYear()),hari:'Idul Fitri',tanggal:today()}),[thrLines,setThrLines]=useState<Row[]>([]);
 const load=async()=>{const {data:p}=await supabase.from('hris_payroll_periods').select('*').order('tanggal_mulai',{ascending:false});setPeriods(p||[]);const selected=(p||[]).find((x:any)=>x.kode===period);if(selected){const {data:r}=await supabase.from('hris_payroll').select('*').eq('periode',period).order('id_karyawan');setRows(r||[]);const {data:ev}=await supabase.from('hris_payroll_events').select('*').in('payroll_id',(r||[]).map((x:any)=>x.id)).order('created_at',{ascending:false});setEvents(ev||[]);const {data:pf}=await supabase.from('hris_payroll_preflight').select('*').eq('period_id',selected.id).order('severity');setPreflight(pf||[]);}};
 useEffect(()=>{load()},[period]);
 const selected=periods.find(p=>p.kode===period); const errors=preflight.filter(x=>x.severity==='ERROR').length; const warnings=preflight.filter(x=>x.severity==='WARNING').length;
 const total=rows.reduce((s,r)=>s+Number(r.gaji_bersih||0),0), employer=rows.reduce((s,r)=>s+Number(r.bpjs||0),0);
 async function preflightRun(){if(!selected)return setMsg('Buka periode payroll terlebih dahulu.');setBusy(true);const {data,error}=await supabase.rpc('hris_v9_preflight',{p_period_id:selected.id});setMsg(error?.message||`Validasi selesai: ${data?.errors||0} error, ${data?.warnings||0} warning.`);setBusy(false);load()}
 async function process(){if(!selected)return setMsg('Pilih periode.');if(errors>0)return setMsg('Payroll ditahan: selesaikan ERROR pada preflight terlebih dahulu.');setBusy(true);const {data,error}=await supabase.rpc('hris_v9_process_payroll',{p_period_id:selected.id});setMsg(error?.message||`Payroll ${data?.period_code||period} berhasil dihitung untuk ${data?.employees||0} karyawan.`);setBusy(false);load()}
 async function createThr(){setBusy(true);const {data,error}=await supabase.rpc('hris_v9_create_thr',{p_year:Number(thr.year),p_hari_raya:thr.hari,p_tanggal_bayar:thr.tanggal});setMsg(error?.message||`THR run dibuat: ${data}`);if(data){const {data:l}=await supabase.from('hris_thr_lines').select('*').eq('thr_run_id',data).order('id_karyawan');setThrLines(l||[]);}setBusy(false)}
 const eventsView=useMemo(()=>events.slice(0,8),[events]);
 return <div className="module-page"><div className="page-heading"><div><span className="group-title">PAYROLL ENGINE V9</span><h1>Indonesian Payroll Control Center</h1><p>Preflight → kalkulasi payroll → statutory → audit lines → approval → payment.</p></div><button className="primary" disabled={busy} onClick={process}>{busy?'Memproses...':'Run Payroll Engine'}</button></div>
 <div className="branch-tabs">{[['engine','Payroll'],['preflight','Preflight'],['thr','THR'],['rules','Statutory Master']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k as any)}>{l}</button>)}</div>
 <div className="toolbar-panel"><label>Periode<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Pilih periode</option>{periods.map(p=><option key={p.id} value={p.kode}>{p.kode} · {p.status}</option>)}</select></label><div className="stat-inline"><b>{rows.length}</b><span>Payroll</span></div><div className="stat-inline"><b>{money(total)}</b><span>Total THP</span></div><div className="stat-inline"><b>{errors}</b><span>Errors</span></div><div className="stat-inline"><b>{warnings}</b><span>Warnings</span></div></div>
 {msg&&<div className="alert">{msg}</div>}
 {tab==='engine'&&<><div className="mini-kpi-row"><div className="stat-card"><span>Gross/Payroll</span><strong>{money(rows.reduce((s,r)=>s+Number(r.total_pendapatan||0),0))}</strong></div><div className="stat-card"><span>Potongan</span><strong>{money(rows.reduce((s,r)=>s+Number(r.total_potongan||0),0))}</strong></div><div className="stat-card"><span>BPJS Employee</span><strong>{money(employer)}</strong></div><div className="stat-card"><span>Audit Events</span><strong>{events.length}</strong></div></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Karyawan</th><th>Pokok</th><th>Lembur</th><th>Gross</th><th>BPJS</th><th>PPh 21</th><th>THP</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.id_karyawan}</b></td><td>{money(r.gaji_pokok)}</td><td>{money(r.lembur)}</td><td>{money(r.total_pendapatan)}</td><td>{money(r.bpjs)}</td><td>{money(r.pph21)}</td><td><b>{money(r.gaji_bersih)}</b></td><td><Status v={r.status}/></td></tr>):<tr><td colSpan={8} className="empty-cell">Belum ada hasil payroll.</td></tr>}</tbody></table></div></div><div className="panel"><h3>Payroll Event Trail</h3>{eventsView.length?eventsView.map(e=><div key={e.id} className="audit-row"><b>{e.event_type}</b><span>{e.from_status||'—'} → {e.to_status||'—'}</span><small>{new Date(e.created_at).toLocaleString('id-ID')}</small></div>):<p>Belum ada event.</p>}</div></>}
 {tab==='preflight'&&<div className="panel"><div className="page-heading"><div><h2>Payroll Preflight</h2><p>Kesalahan ditahan sebelum engine menghitung payroll.</p></div><button className="primary" onClick={preflightRun} disabled={busy||!selected}>{busy?'Validasi...':'Run Preflight'}</button></div><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Karyawan</th><th>Code</th><th>Pesan</th><th>Status</th></tr></thead><tbody>{preflight.length?preflight.map(x=><tr key={x.id}><td><Status v={x.severity}/></td><td>{x.id_karyawan||'—'}</td><td><b>{x.code}</b></td><td>{x.message}</td><td>{x.resolved?'Resolved':'Open'}</td></tr>):<tr><td colSpan={5} className="empty-cell">Belum ada hasil validasi.</td></tr>}</tbody></table></div></div>}
 {tab==='thr'&&<><div className="panel"><h2>THR Engine</h2><p>THR reguler mengikuti prinsip 1 bulan upah untuk masa kerja ≥12 bulan dan proporsional untuk masa kerja 1–&lt;12 bulan.</p><div className="form-grid"><label>Tahun<input type="number" value={thr.year} onChange={e=>setThr({...thr,year:e.target.value})}/></label><label>Hari Raya<input value={thr.hari} onChange={e=>setThr({...thr,hari:e.target.value})}/></label><label>Tanggal Bayar<input type="date" value={thr.tanggal} onChange={e=>setThr({...thr,tanggal:e.target.value})}/></label><button className="primary" onClick={createThr} disabled={busy}>Generate THR</button></div></div><div className="panel table-panel"><table><thead><tr><th>Karyawan</th><th>Masa Kerja</th><th>Upah Dasar</th><th>Proporsi</th><th>THR</th></tr></thead><tbody>{thrLines.length?thrLines.map(x=><tr key={x.id}><td>{x.id_karyawan}</td><td>{Number(x.masa_kerja_bulan).toFixed(1)} bln</td><td>{money(x.upah_dasar)}</td><td>{(Number(x.proporsi)*100).toFixed(1)}%</td><td><b>{money(x.nominal)}</b></td></tr>):<tr><td colSpan={5} className="empty-cell">Generate THR untuk melihat hasil.</td></tr>}</tbody></table></div></>}
 {tab==='rules'&&<Rules/>}
 </div>
}
function Rules(){const [rows,setRows]=useState<Row[]>([]);useEffect(()=>{supabase.from('hris_payroll_rules').select('*').eq('tahun',new Date().getFullYear()).order('kode').then(({data})=>setRows(data||[]))},[]);return <div className="panel table-panel"><h2>Statutory Master</h2><p>Master tarif/ceiling dapat diperbarui tanpa mengubah source code.</p><table><thead><tr><th>Kode</th><th>Nama</th><th>Nilai</th><th>Satuan</th><th>Catatan</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.kode}</b></td><td>{r.nama}</td><td>{r.nilai}</td><td>{r.satuan}</td><td>{r.catatan||'—'}</td></tr>)}</tbody></table></div>}
