import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../../lib/supabase/client';
import '../../../styles/admin/admin.css';

type Row=Record<string, any>;
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const Status=({v}:{v:string})=><span className="status blue">{v||'—'}</span>;

export default function PayrollProductionV22(){
 const [periods,setPeriods]=useState<Row[]>([]),[period,setPeriod]=useState(''),[control,setControl]=useState<Row|null>(null),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{const {data}=await supabase.from('hris_v22_payroll_summary').select('*').order('tanggal_mulai',{ascending:false});setPeriods(data||[]);const p=(data||[]).find((x:any)=>x.kode===period)||(data||[])[0];if(p){if(!period)setPeriod(p.kode);setControl(p);const {data:r}=await supabase.from('hris_payroll').select('*').eq('periode',p.kode).order('id_karyawan');setRows(r||[]);}};
 useEffect(()=>{load()},[]); useEffect(()=>{if(period){const p=periods.find(x=>x.kode===period);if(p){setControl(p);supabase.from('hris_payroll').select('*').eq('periode',period).order('id_karyawan').then(({data})=>setRows(data||[]));}}},[period]);
 const variance=Number(control?.variance_percent||0); const largeVariance=Math.abs(variance)>=10;
 const preview=async()=>{const p=periods.find(x=>x.kode===period);if(!p)return;setBusy(true);const {data,error}=await supabase.rpc('hris_v22_refresh_payroll_control',{p_period_id:p.id});setMsg(error?.message||`Preview selesai: ${data?.employees||0} karyawan.`);setBusy(false);load();};
 const approve=async()=>{const p=periods.find(x=>x.kode===period);if(!p)return;setBusy(true);const {error}=await supabase.rpc('hris_v22_approve_payroll',{p_period_id:p.id,p_note:null});setMsg(error?.message||'Payroll berhasil disetujui.');setBusy(false);load();};
 const lock=async()=>{const p=periods.find(x=>x.kode===period);if(!p)return;if(!confirm('Kunci payroll? Setelah dikunci, nilai finansial tidak dapat diubah.'))return;setBusy(true);const {error}=await supabase.rpc('hris_v22_lock_payroll',{p_period_id:p.id});setMsg(error?.message||'Payroll berhasil dikunci.');setBusy(false);load();};
 const totals=useMemo(()=>({gross:rows.reduce((s,r)=>s+Number(r.total_pendapatan||0),0),ded:rows.reduce((s,r)=>s+Number(r.total_potongan||0),0),net:rows.reduce((s,r)=>s+Number(r.gaji_bersih||0),0)}),[rows]);
 return <div className="module-page"><div className="page-heading"><div><span className="group-title">PAYROLL PRODUCTION V22</span><h1>Payroll Production Control</h1><p>Preview, variance check, approval, final lock, dan kontrol payroll sebelum pembayaran.</p></div><div><button className="secondary" disabled={busy||!period} onClick={preview}>Preview & Recalculate</button>{control?.status==='Preview'&&<button className="primary" disabled={busy} onClick={approve}>Approve Payroll</button>}{control?.status==='Approved'&&<button className="primary" disabled={busy} onClick={lock}>Lock Final</button>}</div></div>
 <div className="toolbar-panel"><label>Periode<select value={period} onChange={e=>setPeriod(e.target.value)}>{periods.map(p=><option key={p.id} value={p.kode}>{p.kode} · {p.status}</option>)}</select></label><div className="stat-inline"><b>{control?.employee_count??rows.length}</b><span>Karyawan</span></div><div className="stat-inline"><b>{money(control?.gross_total??totals.gross)}</b><span>Gross</span></div><div className="stat-inline"><b>{money(control?.net_total??totals.net)}</b><span>THP</span></div><div className="stat-inline"><b>{variance.toFixed(2)}%</b><span>Variance</span></div><Status v={control?.status||'Draft'}/></div>
 {msg&&<div className="alert">{msg}</div>}{largeVariance&&<div className="alert">Peringatan Variance payroll ≥ 10% dari periode final sebelumnya. Lakukan review sebelum approval.</div>}
 <div className="mini-kpi-row"><div className="stat-card"><span>Total Gross</span><strong>{money(control?.gross_total??totals.gross)}</strong></div><div className="stat-card"><span>Total Potongan</span><strong>{money(control?.deduction_total??totals.ded)}</strong></div><div className="stat-card"><span>Total THP</span><strong>{money(control?.net_total??totals.net)}</strong></div><div className="stat-card"><span>Perubahan THP</span><strong>{money(control?.variance_amount||0)}</strong></div></div>
 <div className="panel table-panel"><div className="panel-head"><div><h2>Payroll Detail</h2><p>Data yang akan menjadi dasar slip gaji dan payment batch.</p></div><span>{rows.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Karyawan</th><th>Pokok</th><th>Tunjangan</th><th>Lembur</th><th>Potongan</th><th>BPJS</th><th>PPh 21</th><th>THP</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.id_karyawan}</b></td><td>{money(r.gaji_pokok)}</td><td>{money(r.tunjangan)}</td><td>{money(r.lembur)}</td><td>{money(r.potongan)}</td><td>{money(r.bpjs)}</td><td>{money(r.pph21)}</td><td><b>{money(r.gaji_bersih)}</b></td><td><Status v={r.status}/></td></tr>):<tr><td colSpan={9} className="empty-cell">Belum ada payroll untuk periode ini.</td></tr>}</tbody></table></div></div>
 </div>;
}
