import { useEffect, useState, type FormEvent } from 'react';
import { supabase } from '../../../lib/supabase/client';
import '../../../styles/admin/admin.css';
import AdminIcon from '../common/AdminIcon';

type Row=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);
const money=(n:any)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);

function Heading({title,desc}:{title:string;desc:string}){return <div className="page-heading"><div><h1>{title}</h1><p>{desc}</p></div></div>}
function Branch({tab,setTab,items}:{tab:string;setTab:(v:string)=>void;items:{key:string;label:string}[]}){return <div className="branch-tabs">{items.map(x=><button key={x.key} className={tab===x.key?'active':''} onClick={()=>setTab(x.key)}><AdminIcon name={x.key} size={15}/><span>{x.label}</span></button>)}</div>}
function Empty({cols}:{cols:number}){return <tr><td colSpan={cols} className="empty">Belum ada data.</td></tr>}

export default function HRISCore({employees}:{employees:Row[]}){
 const [tab,setTab]=useState('contracts');
 return <><Heading title="HR Operations" desc="Mesin operasional HR: kontrak, saldo cuti, komponen payroll, exception absensi dan onboarding."/><Branch tab={tab} setTab={setTab} items={[{key:'contracts',label:'Kontrak Karyawan'},{key:'leave',label:'Saldo Cuti'},{key:'components',label:'Komponen Payroll'},{key:'exceptions',label:'Exception Absensi'},{key:'onboarding',label:'Onboarding'}]}/>{tab==='contracts'&&<Contracts employees={employees}/>} {tab==='leave'&&<LeaveBalances employees={employees}/>} {tab==='components'&&<ComponentAssignments employees={employees}/>} {tab==='exceptions'&&<AttendanceExceptions employees={employees}/>} {tab==='onboarding'&&<Onboarding employees={employees}/>}</>
}

function Contracts({employees}:{employees:Row[]}){const [rows,setRows]=useState<Row[]>([]);const [open,setOpen]=useState(false);const [f,setF]=useState({id_karyawan:'',nomor_kontrak:'',jenis_kontrak:'PKWTT',tanggal_mulai:today(),tanggal_selesai:'',jabatan:'',departemen:'',gaji_pokok:'',status:'Aktif'});const load=async()=>{const {data}=await supabase.from('hris_employee_contracts').select('*').order('tanggal_mulai',{ascending:false});setRows(data||[])};useEffect(()=>{load()},[]);async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_employee_contracts').insert({...f,gaji_pokok:Number(f.gaji_pokok)||0,tanggal_selesai:f.tanggal_selesai||null});if(error)alert(error.message);else{setOpen(false);load()}}return <><div className="toolbar"><button className="primary" onClick={()=>setOpen(true)}>+ Kontrak Baru</button></div><div className="panel table-panel"><table><thead><tr><th>Karyawan</th><th>No. Kontrak</th><th>Jenis</th><th>Mulai</th><th>Selesai</th><th>Gaji Pokok</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{employees.find(e=>e.id_karyawan===r.id_karyawan)?.nama||r.id_karyawan}</td><td>{r.nomor_kontrak||'—'}</td><td>{r.jenis_kontrak}</td><td>{r.tanggal_mulai}</td><td>{r.tanggal_selesai||'—'}</td><td>{money(r.gaji_pokok)}</td><td><span className="status-pill">{r.status}</span></td></tr>):<Empty cols={7}/>}</tbody></table></div>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><h3>Kontrak Karyawan</h3><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Karyawan<select required value={f.id_karyawan} onChange={e=>setF({...f,id_karyawan:e.target.value})}><option value="">Pilih karyawan</option>{employees.map(e=><option key={e.id_karyawan} value={e.id_karyawan}>{e.nama} — {e.id_karyawan}</option>)}</select></label><label>No. Kontrak<input value={f.nomor_kontrak} onChange={e=>setF({...f,nomor_kontrak:e.target.value})}/></label><label>Jenis Kontrak<select value={f.jenis_kontrak} onChange={e=>setF({...f,jenis_kontrak:e.target.value})}><option>PKWTT</option><option>PKWT</option><option>Probation</option><option>Freelance</option></select></label><div className="form-grid"><label>Mulai<input type="date" required value={f.tanggal_mulai} onChange={e=>setF({...f,tanggal_mulai:e.target.value})}/></label><label>Selesai<input type="date" value={f.tanggal_selesai} onChange={e=>setF({...f,tanggal_selesai:e.target.value})}/></label></div><div className="form-grid"><label>Jabatan<input value={f.jabatan} onChange={e=>setF({...f,jabatan:e.target.value})}/></label><label>Departemen<input value={f.departemen} onChange={e=>setF({...f,departemen:e.target.value})}/></label></div><label>Gaji Pokok<input type="number" value={f.gaji_pokok} onChange={e=>setF({...f,gaji_pokok:e.target.value})}/></label><button className="primary" type="submit">Simpan Kontrak</button></form></div>}</>}

function LeaveBalances({employees}:{employees:Row[]}){const [rows,setRows]=useState<Row[]>([]);const [types,setTypes]=useState<Row[]>([]);const [f,setF]=useState({id_karyawan:'',leave_type_id:'',tahun:String(new Date().getFullYear()),opening_balance:'12',earned:'12',used:'0',adjustment:'0'});const load=async()=>{const [a,b]=await Promise.all([supabase.from('hris_employee_leave_balances').select('*,hris_leave_types(nama,kode)').order('tahun',{ascending:false}),supabase.from('hris_leave_types').select('*').order('nama')]);setRows(a.data||[]);setTypes(b.data||[])};useEffect(()=>{load()},[]);async function save(e?:FormEvent){e?.preventDefault();const {error}=await supabase.from('hris_employee_leave_balances').upsert({id_karyawan:f.id_karyawan,leave_type_id:f.leave_type_id,tahun:Number(f.tahun),opening_balance:Number(f.opening_balance),earned:Number(f.earned),used:Number(f.used),adjustment:Number(f.adjustment)},{onConflict:'id_karyawan,leave_type_id,tahun'});if(error)alert(error.message);else load()}return <><div className="panel compact-panel"><h3>Set / Koreksi Saldo</h3><div className="form-grid"><select value={f.id_karyawan} onChange={e=>setF({...f,id_karyawan:e.target.value})}><option value="">Karyawan</option>{employees.map(e=><option key={e.id_karyawan} value={e.id_karyawan}>{e.nama}</option>)}</select><select value={f.leave_type_id} onChange={e=>setF({...f,leave_type_id:e.target.value})}><option value="">Jenis Cuti</option>{types.map(t=><option key={t.id} value={t.id}>{t.nama}</option>)}</select><input type="number" value={f.tahun} onChange={e=>setF({...f,tahun:e.target.value})}/><input type="number" placeholder="Opening" value={f.opening_balance} onChange={e=>setF({...f,opening_balance:e.target.value})}/><input type="number" placeholder="Earned" value={f.earned} onChange={e=>setF({...f,earned:e.target.value})}/><input type="number" placeholder="Adjustment" value={f.adjustment} onChange={e=>setF({...f,adjustment:e.target.value})}/><button className="primary" type="button" onClick={()=>save()}>Simpan</button></div></div><div className="panel table-panel"><table><thead><tr><th>Karyawan</th><th>Jenis</th><th>Tahun</th><th>Opening</th><th>Earned</th><th>Used</th><th>Saldo</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{employees.find(e=>e.id_karyawan===r.id_karyawan)?.nama||r.id_karyawan}</td><td>{r.hris_leave_types?.nama||'—'}</td><td>{r.tahun}</td><td>{r.opening_balance}</td><td>{r.earned}</td><td>{r.used}</td><td><b>{Number(r.opening_balance)+Number(r.earned)+Number(r.adjustment)-Number(r.used)}</b></td></tr>):<Empty cols={7}/>}</tbody></table></div></>}

function ComponentAssignments({employees}:{employees:Row[]}){const [rows,setRows]=useState<Row[]>([]);const [components,setComponents]=useState<Row[]>([]);const [f,setF]=useState({id_karyawan:'',komponen_id:'',nominal:'0',tipe:'Tetap',mulai_berlaku:today()});const load=async()=>{const [a,b]=await Promise.all([supabase.from('hris_payroll_component_assignments').select('*,hris_payroll_komponen(nama) ').eq('aktif',true),supabase.from('hris_payroll_komponen').select('*').order('nama')]);setRows(a.data||[]);setComponents(b.data||[])};useEffect(()=>{load()},[]);async function save(e?:FormEvent){e?.preventDefault();const {error}=await supabase.from('hris_payroll_component_assignments').insert({...f,nominal:Number(f.nominal)||0});if(error)alert(error.message);else load()}return <><div className="panel compact-panel"><h3>Penetapan Komponen per Karyawan</h3><div className="form-grid"><select value={f.id_karyawan} onChange={e=>setF({...f,id_karyawan:e.target.value})}><option value="">Karyawan</option>{employees.map(e=><option key={e.id_karyawan} value={e.id_karyawan}>{e.nama}</option>)}</select><select value={f.komponen_id} onChange={e=>setF({...f,komponen_id:e.target.value})}><option value="">Komponen</option>{components.map(c=><option key={c.id} value={c.id}>{c.nama}</option>)}</select><input type="number" placeholder="Nominal" value={f.nominal} onChange={e=>setF({...f,nominal:e.target.value})}/><select value={f.tipe} onChange={e=>setF({...f,tipe:e.target.value})}><option>Tetap</option><option>Persentase</option><option>Formula</option></select><input type="date" value={f.mulai_berlaku} onChange={e=>setF({...f,mulai_berlaku:e.target.value})}/><button className="primary" type="button" onClick={()=>save()}>Tetapkan</button></div></div><div className="panel table-panel"><table><thead><tr><th>Karyawan</th><th>Komponen</th><th>Tipe</th><th>Nominal</th><th>Berlaku</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{employees.find(e=>e.id_karyawan===r.id_karyawan)?.nama||r.id_karyawan}</td><td>{r.hris_payroll_komponen?.nama||r.komponen_id}</td><td>{r.tipe}</td><td>{money(r.nominal)}</td><td>{r.mulai_berlaku}</td></tr>):<Empty cols={5}/>}</tbody></table></div></>}

function AttendanceExceptions({employees}:{employees:Row[]}){const [rows,setRows]=useState<Row[]>([]);const [f,setF]=useState({id_karyawan:'',tanggal:today(),tipe:'Lupa Absen',alasan:''});const load=async()=>{const {data}=await supabase.from('hris_attendance_exceptions').select('*').order('created_at',{ascending:false}).limit(500);setRows(data||[])};useEffect(()=>{load()},[]);async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_attendance_exceptions').insert(f);if(error)alert(error.message);else{setF({...f,alasan:''});load()}}return <><div className="panel compact-panel"><h3>Ajukan Exception</h3><div className="form-grid"><select value={f.id_karyawan} onChange={e=>setF({...f,id_karyawan:e.target.value})}><option value="">Karyawan</option>{employees.map(e=><option key={e.id_karyawan} value={e.id_karyawan}>{e.nama}</option>)}</select><input type="date" value={f.tanggal} onChange={e=>setF({...f,tanggal:e.target.value})}/><select value={f.tipe} onChange={e=>setF({...f,tipe:e.target.value})}><option>Lupa Absen</option><option>Koreksi Jam Masuk</option><option>Koreksi Jam Pulang</option><option>Dinas</option><option>Remote</option></select><input placeholder="Alasan" value={f.alasan} onChange={e=>setF({...f,alasan:e.target.value})}/><button className="primary" onClick={save}>Ajukan</button></div></div><div className="panel table-panel"><table><thead><tr><th>Tanggal</th><th>Karyawan</th><th>Jenis</th><th>Alasan</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.tanggal}</td><td>{employees.find(e=>e.id_karyawan===r.id_karyawan)?.nama||r.id_karyawan}</td><td>{r.tipe}</td><td>{r.alasan||'—'}</td><td><span className="status-pill">{r.status}</span></td></tr>):<Empty cols={5}/>}</tbody></table></div></>}

function Onboarding({employees}:{employees:Row[]}){const [rows,setRows]=useState<Row[]>([]);const [f,setF]=useState({id_karyawan:'',task:'Lengkapi dokumen karyawan',owner:'HRD',due_date:today()});const load=async()=>{const {data}=await supabase.from('hris_onboarding_tasks').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{load()},[]);async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_onboarding_tasks').insert(f);if(error)alert(error.message);else load()}async function complete(id:string){const {error}=await supabase.from('hris_onboarding_tasks').update({status:'Completed',completed_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else load()}return <><div className="panel compact-panel"><h3>Onboarding Checklist</h3><div className="form-grid"><select value={f.id_karyawan} onChange={e=>setF({...f,id_karyawan:e.target.value})}><option value="">Karyawan</option>{employees.map(e=><option key={e.id_karyawan} value={e.id_karyawan}>{e.nama}</option>)}</select><input value={f.task} onChange={e=>setF({...f,task:e.target.value})}/><input value={f.owner} onChange={e=>setF({...f,owner:e.target.value})}/><input type="date" value={f.due_date} onChange={e=>setF({...f,due_date:e.target.value})}/><button className="primary" onClick={save}>Tambah Task</button></div></div><div className="panel table-panel"><table><thead><tr><th>Karyawan</th><th>Task</th><th>Owner</th><th>Due</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{employees.find(e=>e.id_karyawan===r.id_karyawan)?.nama||r.id_karyawan}</td><td>{r.task}</td><td>{r.owner||'—'}</td><td>{r.due_date||'—'}</td><td><span className="status-pill">{r.status}</span></td><td>{r.status!=='Completed'&&<button className="secondary" onClick={()=>complete(r.id)}>Selesai</button>}</td></tr>):<Empty cols={6}/>}</tbody></table></div></>}
